
#ifndef PROJETS_COREDEFINE_H
#define PROJETS_COREDEFINE_H

# define SIZE_OF_PIECE 4
# define NUMBER_OF_PIECE 7
# define NUMBER_OF_ROTATION 4

# define MATRIX_X_LENGTH 10
# define MATRIX_Y_LENGTH 20

#endif //PROJETS_COREDEFINE_H
